name: Bump version on push

on:
  push:
    branches: [ main ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging

    - name: Get current version and bump
      id: version
      run: |
        import re
        import os
        import sys
        from packaging import version

        def log(message):
            print(f"LOG: {message}")
            sys.stdout.flush()

        try:
            log("Current working directory: " + os.getcwd())
            log("Contents of current directory: " + str(os.listdir()))

            init_file = './core/__init__.py'
            if not os.path.exists(init_file):
                raise FileNotFoundError(f"Cannot find {init_file}")

            with open(init_file, 'r') as f:
                content = f.read()
                log("Content of __init__.py: " + content)
                match = re.search(r'__version__\s*=\s*["\'](.+?)["\']', content)
                if not match:
                    raise ValueError("Version string not found in __init__.py")
                current_version = match.group(1)

            log(f"Current version: {current_version}")
            new_version = version.parse(current_version)
            new_version = version.parse(f"{new_version.major}.{new_version.minor}.{new_version.micro + 1}")
            log(f"New version: {new_version}")

            with open(init_file, 'w') as f:
                new_content = re.sub(r'(__version__\s*=\s*["\'])(.+?)(["\'])', f'\\g<1>{new_version}\\g<3>', content)
                f.write(new_content)

            print(f"::set-output name=new_version::{new_version}")
            print(f"::set-output name=new_tag::v{new_version}")
        except Exception as e:
            log(f"Error: {str(e)}")
            raise
      shell: python

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git status
        git diff --staged --quiet || (git commit -m "Bump version to ${{ steps.version.outputs.new_version }}" --allow-empty)
        git tag ${{ steps.version.outputs.new_tag }} || echo "Failed to create tag"
        git push || echo "Failed to push commits"
        git push --tags || echo "Failed to push tags"
      continue-on-error: true

    - name: Output new version
      if: steps.version.outputs.new_version
      run: echo "New version - ${{ steps.version.outputs.new_version }}"

    - name: Check for errors
      if: failure()
      run: |
        echo "The workflow failed. Please check the logs for more information."
        exit 1