name: Bump version on push

on:
  push:
    branches: [ main ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install packaging

    - name: Get current version and bump
      id: version
      run: |
        import re
        import os
        from packaging import version

        with open('./core/__init__.py', 'r') as f:
            content = f.read()
            current_version = re.search(r'__version__\s*=\s*["\'](.+?)["\']', content).group(1)

        new_version = version.parse(current_version)
        new_version = version.parse(f"{new_version.major}.{new_version.minor}.{new_version.micro + 1}")

        with open('./core/__init__.py', 'w') as f:
            f.write(re.sub(r'(__version__\s*=\s*["\'])(.+?)(["\'])', f'\\1{new_version}\\3', content))

        print(f"::set-output name=new_version::{new_version}")
        print(f"::set-output name=new_tag::v{new_version}")
      shell: python

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Bump version to ${{ steps.version.outputs.new_version }}" --allow-empty
        git tag ${{ steps.version.outputs.new_tag }}
        git push && git push --tags

    - name: Output new version
      run: echo "New version - ${{ steps.version.outputs.new_version }}"